---
- name: Configure web server
  hosts: all
  become: yes
  vars:
    hello_content: "{{ lookup('file', '../hello.txt') }}"
  
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy nginx config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default

    - name: Create index.html
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Hello Page</title>
          </head>
          <body>
              <pre>{{ hello_content }}</pre>
          </body>
          </html>
        dest: /var/www/html/index.html
        mode: 0644

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
