name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.3.7"

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="bucket_name=my-unique-bucket-name-$GITHUB_RUN_ID"
      working-directory: ./terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Get EC2 Public DNS
      id: get-dns
      run: echo "public_dns=$(terraform output -raw public_dns)" >> $GITHUB_OUTPUT
      working-directory: ./terraform

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Configure inventory
      run: |
        echo "[webservers]" > inventory.ini
        echo "${{ steps.get-dns.outputs.public_dns }} ansible_user=ubuntu" >> inventory.ini

    - name: Run Ansible playbook
      run: ansible-playbook -i inventory.ini ansible/deploy.yml --ssh-common-args='-o StrictHostKeyChecking=no'
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
