name: Reset AWS to Default

on:
  workflow_dispatch:

jobs:
  cleanup-and-reset:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # поменяй на свою

    - name: Initialize Terraform
      run: terraform init

    - name: Destroy All Resources
      run: terraform destroy -auto-approve

    - name: Apply Standard Configuration
      run: terraform apply -auto-approve
